//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLXD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class VATLIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VATLIEU()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
        }
    
        [Display(Name = "Mã vật liệu")]
        public int MaVL { get; set; }
        [Display(Name ="Tên vật liệu")]
        public string TenVL { get; set; }
        [Display(Name = "Đơn vị")]
        public string DonVi { get; set; }
        [Display(Name = "Giá vật liệu")]
        public Nullable<decimal> GiaVL { get; set; }
        [Display(Name = "Mã loại vật liệu")]
        public Nullable<int> MaLoaiVL { get; set; }
        [Display(Name = "Hình vật liệu")]
        public string HinhVL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual LOAIVATLIEU LOAIVATLIEU { get; set; }
    }
}
